import ComingSoon from '@/components/ComingSoon'
import { Head } from 'next/head'

export default function Home() {
  /*
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { Head } from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {

  const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  return (
    <html lang="en">
      <Head>
        <meta name="title" content={metadata.title} />
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}


  */
  return (
    <>
    <Head>
      <title>Portfolio David</title>
      <meta name='description' content='Personal Portfolio create with Next JS' />
      <link rel='icon' href='favicon.ico' />
    </Head>
    <ComingSoon />
    </>
  )
}
