import './../styles/globals.css'
import { Inter } from 'next/font/google'
import { Metadata } from 'next'

export default function RootLayout({ children }) {

  const inter = Inter({ subsets: ['latin'] })

  const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  return (
    <html lang="en">
      <head>
        <meta name="title" content={metadata.title} />
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
